# pod-display-ingress.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pod-display-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ip-172-31-40-97
    http:
      paths:
      - path: /pod1
        pathType: Prefix
        backend:
          service:
            name: pod-display-deployment
            port:
              number: 80
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header POD_UID "1";
      - path: /pod2
        pathType: Prefix
        backend:
          service:
            name: pod-display-deployment
            port:
              number: 80
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header POD_UID "2";
      - path: /pod3
        pathType: Prefix
        backend:
          service:
            name: pod-display-deployment
            port:
              number: 80
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header POD_UID "3";