# pod-display-configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-display-configmap
data:
  pod-uid-values.yaml: |
    - path: /pod1
      uid: "1"
    - path: /pod2
      uid: "2"
    - path: /pod3
      uid: "3"