# pod-display-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-display-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-display
  template:
    metadata:
      labels:
        app: pod-display
    spec:
      containers:
      - name: pod-display-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
          readOnly: true
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid