# pod-display-ingress.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pod-display-ingress
spec:
  rules:
  - host: your-ingress-host.com
    http:
      paths:
      - path: /pod1
        pathType: Prefix
        backend:
          service:
            name: pod-display-service
            port:
              number: 80
        value: POD_UID=1
      - path: /pod2
        pathType: Prefix
        backend:
          service:
            name: pod-display-service
            port:
              number: 80
        value: POD_UID=2
      - path: /pod3
        pathType: Prefix
        backend:
          service:
            name: pod-display-service
            port:
              number: 80
        value: POD_UID=3